### ISSUE TITLE
Can't receive logs from the frontend, while logs from backend work

### ISSUE THREAD

**Issue by Dizotoff** [axiomhq/next-axiom#114]
I have installed Vercel Axiom integration into my project and wrapped my Next.js config in `withAxiom`. 

I can see my backend logs in place, everything works there. But I can not see any frontend logs using 

```
import { log } from `next-axiom`;

// pages/index.js
function home() {
    ...
    log.debug('User logged in', { userId: 42 })
    ...
}
```

Every time I trigger the log from the frontend I receive: 

```
{
  "request": {
    "destination": "https://vercel-vitals.axiom.co/api/v1/send?
    "method": "POST",
    "path": "/_axiom/logs",
    "scheme": "https",
    "statusCode": 403,
    ...
  },
...
}
```

It's not the full log, but you got the problem.

I'm using Next 13. I noticed that Web-Vitals are not supported with Next 13, but frontend logging should still work, right?

Am I doing something wrong?

**Comment by brunocangs** [comment]
Same here, even tried to apply the env variables as instructed although it was a vercel deployment

**Comment by schehata** [comment]
@brunocangs the vercel integration doesn't require adding env variables because it already does add one `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` you can remove the others if you added them and redeploy so that the env variables take effect. 

@Dizotoff @MrT3313 is the same for you, you've added env variables with the vercel integration? from the error I see that you receive forbidden, which means either your token or ingest endpoint is not correct.

**Comment by schehata** [comment]
can you guys check again if your problem is solved? checkout @bahlo 's [response](https://github.com/axiomhq/next-axiom/issues/115#issuecomment-1506639848) on another issue that might be realted.

**Comment by matthewlilley** [comment]
Having the same issue, haven't set a custom env for NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT, it seems that front-end logs aren't making it through. Tried reporting via support but realised there is no support system but Discord, reported to Vercel numerous times as well.
