### ISSUE TITLE
Can't see the logs printed out in production

### ISSUE THREAD

**Issue by lumenwrites** [axiomhq/next-axiom#54]
Hi! I'm new to Axiom, this looks like an awesome tool, thank you for building it!

I'm trying to set it up with Next.js and Vercel, and ran into an issue - in my production deployment, I don't see the logs printed out in the devtools console or in the function logs in Vercel's UI. 

In your README it says:

> When env vars are not detected, Pretty printing to console is enabled by default, to disable it set the environment variable:
> AXIOM_PRETTY_PRINT_ENABLED=false

My guess was that if I'd set this variable to true in production, it should enable printing the logs into the console, but it doesn't look like it's working. Even with this variable set to true, I don't see errors in my devtools.

Can you help me out? How can I enable pretty printing logs in production?

**Comment by bahlo** [comment]
The pretty print only affects how logs are formatted and is only enabled on non-prod builds.

If you use the logger provided by this library logs are sent to Axiom directly on prod builds and not printed to console. If we printed them to we'd have duplicates because we capture the stdout of functions as well.

One solution would be to switch to `console.log` in you function, at the cost of parsed fields and metadata.

**Comment by bahlo** [comment]
@lumenwrites I hope this solved your problem, if it didn't please re-open 🙏🏻

**Comment by jsw** [comment]
> 

Can you point to this logic in the codebase? I am seeing logs printed in the console *and* sent to axiom, and trying to understand how that is happening.
